### ISSUE TITLE
killgrave open source contribution

### ISSUE THREAD

**Issue by kiblitz** [joanlopez/joanlopez#1]
Hi!

I'm currently a CS college student. I was looking at several open source projects on github when I came across killgrave. I was wondering if and how I could get involved. In particular, I wasn't able to join the slack channel (seems like I need to be explicitly invited?).

Thanks!

**Comment by joanlopez** [comment]
Hi @kiblitz,

Nice to meet you! 😊  Yeah, it's always nice to see new faces around the Killgrave project. You're completely welcome to take any _unassigned_ and to start working on it.

Regarding #killgrave Slack channel on Gophers workspace, it's a public channel so you should be able to join it. 
What's the specific error you're encountering when trying to join it? 🤔 

Thanks!!

**Comment by kiblitz** [comment]
Hi @joanlopez,
Thanks for the reply! Upon signing into Slack after clicking the link, I get an error that says my email doesn't have an account on this workspace.

**Comment by joanlopez** [comment]
So, you're not able to login into the Gophers' Slack at all? If that's the case, try to create a new account at https://gophers.slack.com.

**Comment by kiblitz** [comment]
There seems to be no way to create an account on that link, only sign-in to an existing account which gives me the error I've mentioned above.

**Comment by joanlopez** [comment]
Gotcha! Then, can you try this link, please?
https://invite.slack.golangbridge.org/

**Comment by kiblitz** [comment]
It worked! Thanks!
